### ISSUE TITLE
Full Storage Bug

### ISSUE THREAD

**Issue by humdedum1** [sumghai/Replimat#37] opened 2020-06-12 12:11 UTC
Hi Sumghai, there's currently an issue with Pick Up and Haul + Replimat + Deep Storage.

> JobDriver threw exception in initAction for pawn Dog driver=JobDriver_UnloadYourHauledInventory (toilIndex=1) driver.job=(UnloadYourHauledInventory (Job_1573179) A=Thing_Human12787)
> System.NullReferenceException: Object reference not set to an instance of an object
>   at Replimat.ReplimatMod+StoreUtility_NoStorageBlockersIn.ReplimatHopperFilledEnough (System.Boolean& __result, Verse.IntVec3 c, Verse.Map map, Verse.Thing thing) [0x00018] in <08f22a49ca55465693b94ab5f56a6f32>:0 
>   at (wrapper dynamic-method) RimWorld.StoreUtility.DMD<DMD<NoStorageBlockersIn_Patch3>?-1387068544::NoStorageBlockersIn_Patch3>(Verse.IntVec3,Verse.Map,Verse.Thing)
>   at (wrapper dynamic-method) RimWorld.StoreUtility.DMD<DMD<IsGoodStoreCell_Patch1>?563324928::IsGoodStoreCell_Patch1>(Verse.IntVec3,Verse.Map,Verse.Thing,Verse.Pawn,RimWorld.Faction)
>   at RimWorld.StoreUtility.TryFindStoreCellNearColonyDesperate (Verse.Thing item, Verse.Pawn carrier, Verse.IntVec3& storeCell) [0x000f2] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
>   at PickUpAndHaul.JobDriver_UnloadYourHauledInventory+<>c__DisplayClass4_0.<MakeNewToils>b__0 () [0x00046] in <ac2642f61fbf46c5810ed34fcf95bf58>:0 
>   at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001df] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
> Verse.Log:Error(String, Boolean)
> Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:DMD<DMD<DriverTick_Patch1>?-1253296512::DriverTick_Patch1>(JobDriver)
> Verse.AI.Pawn_JobTracker:JobTrackerTick()
> Verse.Pawn:DMD<DMD<Tick_Patch1>?-484448768::Tick_Patch1>(Pawn)
> Verse.TickList:DMD<DMD<Tick_Patch2>?-229652352::Tick_Patch2>(TickList)
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:DMD<DMD<UpdatePlay_Patch1>?1982821504::UpdatePlay_Patch1>(Game)
> Verse.Root_Play:DMD<DMD<Update_Patch1>?701600256::Update_Patch1>(Root_Play)

The scenario to replicate this that I used, was have two pawns haul chunks to a wooden crate close to capacity. Whoever won the race got to unload their inventory. Second pawn stands around confused for a couple of ticks, moves on, but requeues said job, causing it to loop indefinitely.
This happens without having anything from Replimat built, so I assume that both DS and Replimat touching NoStorageBlockersIn is either breaking eachother, or one breaking the other. Dubs has been pinged on his Discord server to see if he too is familiar with it. I'm not particularly familiar with RW code, so I'm only assuming here.

**Comment by KragV** [comment] 2020-06-15 23:00
Same issue here
https://gist.github.com/HugsLibRecordKeeper/d6b09c3c4cd4145bd9132c27322c6201

**Comment by sumghai** [comment] 2020-06-16 10:26
I'll take a look at this when I have time.

@KragV - Please don't send me HugsLib logs, as I have no use for them.

**Comment by sumghai** [comment] 2020-07-05 07:47
@humdedum1, I have not been able to reproduce your issue.

I am currently running the latest versions of all three mods:
- Replimat v1.1.2 (22 Apr 2020)
- LWM's Deep Storage v1.1.0.10 (16 June 2020)
- Pick Up and Haul v1.1.0 (3 March 2020)

I set up a scenario similar to yours where two pawns were both tasked with hauling wood logs to the same Wooden Pallet (I could not find any building called a Wooden Crate in my architect menu).

The result was that both pawns simultaneously hauled to the Pallet without any errors.

Since you originally reported this issue on 12 June 2020, it is possible that the latest update of Deep Storage may have already fixed the problem. Could you please try again?

**Comment by sumghai** [comment] 2020-07-06 13:29
Actually, @humdedum1 and @KragV, are you two running the Steam version of the Replimat mod?

I suspect that the reported issue is related to #34, which has been fixed in dev, but not yet published as a release. Could you two please try the following dev build?

https://github.com/sumghai/Replimat/archive/9fc00e2cfdb7675128979a23ca43f9347f542b40.zip

**Comment by sumghai** [comment] 2020-07-10 12:17
Neither @humdedum1 and @KragV have responded in time, I'm going to assume that the fix for #34 is also applicable here.

**Closed** 2020-07-10 12:17 UTC
Labels: Bug
