### ISSUE TITLE
Cadaver Processor cannot be placed

### ISSUE THREAD

**Issue by SektorDV** [sumghai/Replimat#72] opened 2022-11-14 03:00 UTC
**Describe the bug:**  
Trying to place/build a cadaver processor causes the processor to immediately disappear.

**Expected behavior:**  
The processor should be built normally.

**Steps to reproduce:**  

1. Attempt to build a cadaver processor/place a minified cadaver processor via debug mode.

**Additional information:**
The log shows a null reference error,

## System and Game Configuration
**Operating System:** Ubuntu 20.04 64bit
**Physical RAM:** 32GB
**RimWorld base game version:** 1.4.3542
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech
**Replimat mod version:** 1.4.2
**Replimat mod downloaded from:** Steam
**Your mod list:**
- Id: brrainz.harmony
- Id: ludeon.rimworld
- Id: ludeon.rimworld.royalty
- Id: ludeon.rimworld.ideology
- Id: ludeon.rimworld.biotech
- Id: sumghai.replimat
- Id: erdelf.humanoidalienraces

(all latest versions from steam workshop)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2022-11-14 05:23
You have too many mods in your modlist.

Please cut your modlist to less than 5 mods, and confirm that the issue still occurs.

Also, "all latest versions from steam workshop" is not an adequate response - I need exact version numbers for each mod.

**Comment by SektorDV** [comment] 2022-11-14 14:51
alright, i'll try to narrow it down to fewer mods and get back to you

**Comment by SektorDV** [comment] 2022-11-14 21:06
update: i narrowed it down. the problem seems to only occur when humanoid alien races (1.0.0) is enabled

**Comment by sumghai** [comment] 2022-11-19 03:02
I cannot reproduce the issue as currently described, using v1.4.3542 of Core/Royalty/Ideology/Biotech, Replimat v1.4.2 and HAR 18 Nov 2022 update.

I was able to place the Processors directly in god mode or build them normally without any nullref errors.

Could you check if you have downloaded the latest version of HAR from Steam, and try again?

**Comment by sumghai** [comment] 2022-11-23 07:41
I still cannot reproduce the issue as currently described using v1.4.3555 of Core/Royalty/Ideology/Biotech, Replimat v1.4.3 and HAR 18 Nov 2022 update.

I was able to place the Processors directly in god mode or build them normally without any nullref errors.

Please check that you have downloaded the latest version of Replimat and HAR from Steam, delete all your configs, start a new temporary savegame with just these mods and try to recreate this issue.

If you have a savefile where the issue can be reproduced (with only Harmony, Core, HAR and Replimat), put it in a ZIP archive, then drag and drop it directly into your reply to upload it.

**Comment by sumghai** [comment] 2022-11-26 01:44
Closing due to lack of follow up from reporting user.

**Closed** 2022-11-26 01:44 UTC
Labels: Invalid / Won't Fix / No Follow-Up, Bug, Needs More Info

**Comment by SektorDV** [comment] 2023-01-23 10:35
Sorry for the extremely late followup - I did some more testing yesterday, and it seems to be related not so much to HAR, but the way that HAR interacts with Jecrell's Rim of Madness Vampires - removing either just HAR, or just Vampires, seems to fix the issue for me. Weird, since HAR isn't a RoMV dependency.

**Comment by sumghai** [comment] 2023-01-25 04:53
If it's an incompatibility/bug between HAR and RoMV that's spilling over into Replimat, that's not something I can fix myself.
