### ISSUE TITLE
Activating the hopper seems to demand an enormous amount of power

### ISSUE THREAD

**Issue by AndiLeni** [sumghai/Replimat#82] opened 2023-08-12 14:07 UTC
**Describe the bug:**  
Activating the hopper seems to demand an enormous amount of power

**Expected behavior:**  
The power should not extend 2000w if I am not mistaken.

**Steps to reproduce:**  

1. not sure

**Additional information:**
![20230812155618_1](https://github.com/sumghai/Replimat/assets/13385771/c79c1a5c-4de2-4591-94b9-21e99d162575)

## System and Game Configuration
**Operating System:**Microsoft Windows 10 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.4.3704
**RimWorld DLCs loaded:** all
**Replimat mod version:** 1.4.7
**Replimat mod downloaded from:** Steam
**Your mod list:** 
```xml
<?xml version="1.0" encoding="utf-8"?>
<savedModList>
	<meta>
		<gameVersion>1.4.3704 rev896</gameVersion>
		<modIds>
			<li>brrainz.harmony</li>
			<li>ludeon.rimworld</li>
			<li>ludeon.rimworld.royalty</li>
			<li>unlimitedhugs.hugslib</li>
			<li>orion.cashregister</li>
			<li>orion.hospitality</li>
			<li>adamas.storefront</li>
			<li>adamas.vendingmachines</li>
			<li>dubwise.dubsbadhygiene</li>
			<li>adamas.hospitalityspa</li>
			<li>oskarpotocki.vanillafactionsexpanded.core</li>
			<li>vanillaexpanded.vfecore</li>
			<li>adamas.hospitalitycasino</li>
			<li>adamas.hospital</li>
			<li>sumghai.replimat</li>
			<li>vanillaexpanded.vcooke</li>
			<li>vanillaexpanded.vcookestews</li>
			<li>vanillaexpanded.vfepower</li>
			<li>vanillaexpanded.vchemfuele</li>
			<li>vanillaexpanded.vgeneticse</li>
			<li>vanillaexpanded.vanillasocialinteractionsexpanded</li>
			<li>vanillaexpanded.vwe</li>
			<li>vanillaexpanded.vweq</li>
			<li>vanillaexpanded.vwec</li>
			<li>vanillaexpanded.vplantse</li>
			<li>vanillaexpanded.vplantsemore</li>
			<li>vanillaexpanded.vnutriente</li>
			<li>vanillaexpanded.vcef</li>
			<li>vanillaexpanded.vcefaddon</li>
			<li>vanillaexpanded.vbrewe</li>
			<li>vanillaexpanded.vbrewecandt</li>
			<li>ogre.ogrestack</li>
			<li>ludeon.rimworld.ideology</li>
			<li>ludeon.rimworld.biotech</li>
			<li>m00nl1ght.mappreview</li>
			<li>murmur.walllight</li>
			<li>vanillaexpanded.vwenl</li>
			<li>vanillaexpanded.vwel</li>
			<li>vanillaexpanded.vanillatradingexpanded</li>
			<li>vanillaexpanded.vtexe</li>
			<li>vanillaexpanded.vplantsesucculents</li>
			<li>vanillaexpanded.vfespacer</li>
			<li>vanillaexpanded.vfesecurity</li>
			<li>vanillaexpanded.vfepropsanddecor</li>
			<li>vanillaexpanded.vfeproduction</li>
			<li>vanillaexpanded.vfemedical</li>
			<li>vanillaexpanded.vfefarming</li>
			<li>vanillaexpanded.vfeart</li>
			<li>vanillaexpanded.vfearchitect</li>
			<li>vanillaexpanded.vee</li>
			<li>vanillaexpanded.vbookse</li>
			<li>vanillaexpanded.basegeneration</li>
			<li>vanillaexpanded.varme</li>
			<li>uuugggg.replacestuff</li>
			<li>mehni.pickupandhaul</li>
		</modIds>
		<modSteamIds>
			<li>0</li>
			<li>0</li>
			<li>1149640</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>1392840</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
			<li>0</li>
		</modSteamIds>
		<modNames>
			<li>Harmony</li>
			<li>Core</li>
			<li>Royalty</li>
			<li>HugsLib</li>
			<li>Cash Register</li>
			<li>Hospitality</li>
			<li>Hospitality: Storefront</li>
			<li>Hospitality: Vending machines</li>
			<li>Dubs Bad Hygiene</li>
			<li>Hospitality: Spa</li>
			<li>Vanilla Expanded Framework</li>
			<li>Vanilla Furniture Expanded</li>
			<li>Hospitality: Casino</li>
			<li>Hospital</li>
			<li>Replimat</li>
			<li>Vanilla Cooking Expanded</li>
			<li>Vanilla Cooking Expanded - Stews</li>
			<li>Vanilla Furniture Expanded - Power</li>
			<li>Vanilla Chemfuel Expanded</li>
			<li>Vanilla Genetics Expanded</li>
			<li>Vanilla Social Interactions Expanded</li>
			<li>Vanilla Weapons Expanded</li>
			<li>Vanilla Weapons Expanded - Quickdraw</li>
			<li>Vanilla Weapons Expanded - Coilguns</li>
			<li>Vanilla Plants Expanded</li>
			<li>Vanilla Plants Expanded - More Plants</li>
			<li>Vanilla Nutrient Paste Expanded</li>
			<li>Vanilla Fishing Expanded</li>
			<li>Vanilla Fishing Expanded - Fishing Treasures AddOn</li>
			<li>Vanilla Brewing Expanded</li>
			<li>Vanilla Brewing Expanded - Coffees and Teas</li>
			<li>OgreStack</li>
			<li>Ideology</li>
			<li>Biotech</li>
			<li>Map Preview</li>
			<li>Wall Light</li>
			<li>Vanilla Weapons Expanded - Non-Lethal</li>
			<li>Vanilla Weapons Expanded - Laser</li>
			<li>Vanilla Trading Expanded</li>
			<li>Vanilla Textures Expanded</li>
			<li>Vanilla Plants Expanded - Succulents</li>
			<li>Vanilla Furniture Expanded - Spacer Module</li>
			<li>Vanilla Furniture Expanded - Security</li>
			<li>Vanilla Furniture Expanded - Props and Decor</li>
			<li>Vanilla Furniture Expanded - Production</li>
			<li>Vanilla Furniture Expanded - Medical Module</li>
			<li>Vanilla Furniture Expanded - Farming</li>
			<li>Vanilla Furniture Expanded - Art</li>
			<li>Vanilla Furniture Expanded - Architect</li>
			<li>Vanilla Events Expanded</li>
			<li>Vanilla Books Expanded</li>
			<li>Vanilla Base Generation Expanded</li>
			<li>Vanilla Armour Expanded</li>
			<li>Replace Stuff</li>
			<li>Pick Up And Haul</li>
		</modNames>
	</meta>
	<modList>
		<ids>
			<li>brrainz.harmony</li>
			<li>ludeon.rimworld</li>
			<li>ludeon.rimworld.royalty</li>
			<li>unlimitedhugs.hugslib</li>
			<li>orion.cashregister</li>
			<li>orion.hospitality</li>
			<li>adamas.storefront</li>
			<li>adamas.vendingmachines</li>
			<li>dubwise.dubsbadhygiene</li>
			<li>adamas.hospitalityspa</li>
			<li>oskarpotocki.vanillafactionsexpanded.core</li>
			<li>vanillaexpanded.vfecore</li>
			<li>adamas.hospitalitycasino</li>
			<li>adamas.hospital</li>
			<li>sumghai.replimat</li>
			<li>vanillaexpanded.vcooke</li>
			<li>vanillaexpanded.vcookestews</li>
			<li>vanillaexpanded.vfepower</li>
			<li>vanillaexpanded.vchemfuele</li>
			<li>vanillaexpanded.vgeneticse</li>
			<li>vanillaexpanded.vanillasocialinteractionsexpanded</li>
			<li>vanillaexpanded.vwe</li>
			<li>vanillaexpanded.vweq</li>
			<li>vanillaexpanded.vwec</li>
			<li>vanillaexpanded.vplantse</li>
			<li>vanillaexpanded.vplantsemore</li>
			<li>vanillaexpanded.vnutriente</li>
			<li>vanillaexpanded.vcef</li>
			<li>vanillaexpanded.vcefaddon</li>
			<li>vanillaexpanded.vbrewe</li>
			<li>vanillaexpanded.vbrewecandt</li>
			<li>ogre.ogrestack</li>
			<li>ludeon.rimworld.ideology</li>
			<li>ludeon.rimworld.biotech</li>
			<li>m00nl1ght.mappreview</li>
			<li>murmur.walllight</li>
			<li>vanillaexpanded.vwenl</li>
			<li>vanillaexpanded.vwel</li>
			<li>vanillaexpanded.vanillatradingexpanded</li>
			<li>vanillaexpanded.vtexe</li>
			<li>vanillaexpanded.vplantsesucculents</li>
			<li>vanillaexpanded.vfespacer</li>
			<li>vanillaexpanded.vfesecurity</li>
			<li>vanillaexpanded.vfepropsanddecor</li>
			<li>vanillaexpanded.vfeproduction</li>
			<li>vanillaexpanded.vfemedical</li>
			<li>vanillaexpanded.vfefarming</li>
			<li>vanillaexpanded.vfeart</li>
			<li>vanillaexpanded.vfearchitect</li>
			<li>vanillaexpanded.vee</li>
			<li>vanillaexpanded.vbookse</li>
			<li>vanillaexpanded.basegeneration</li>
			<li>vanillaexpanded.varme</li>
			<li>uuugggg.replacestuff</li>
			<li>mehni.pickupandhaul</li>
		</ids>
		<names>
			<li>Harmony</li>
			<li>Core</li>
			<li>Royalty</li>
			<li>HugsLib</li>
			<li>Cash Register</li>
			<li>Hospitality</li>
			<li>Hospitality: Storefront</li>
			<li>Hospitality: Vending machines</li>
			<li>Dubs Bad Hygiene</li>
			<li>Hospitality: Spa</li>
			<li>Vanilla Expanded Framework</li>
			<li>Vanilla Furniture Expanded</li>
			<li>Hospitality: Casino</li>
			<li>Hospital</li>
			<li>Replimat</li>
			<li>Vanilla Cooking Expanded</li>
			<li>Vanilla Cooking Expanded - Stews</li>
			<li>Vanilla Furniture Expanded - Power</li>
			<li>Vanilla Chemfuel Expanded</li>
			<li>Vanilla Genetics Expanded</li>
			<li>Vanilla Social Interactions Expanded</li>
			<li>Vanilla Weapons Expanded</li>
			<li>Vanilla Weapons Expanded - Quickdraw</li>
			<li>Vanilla Weapons Expanded - Coilguns</li>
			<li>Vanilla Plants Expanded</li>
			<li>Vanilla Plants Expanded - More Plants</li>
			<li>Vanilla Nutrient Paste Expanded</li>
			<li>Vanilla Fishing Expanded</li>
			<li>Vanilla Fishing Expanded - Fishing Treasures AddOn</li>
			<li>Vanilla Brewing Expanded</li>
			<li>Vanilla Brewing Expanded - Coffees and Teas</li>
			<li>OgreStack</li>
			<li>Ideology</li>
			<li>Biotech</li>
			<li>Map Preview</li>
			<li>Wall Light</li>
			<li>Vanilla Weapons Expanded - Non-Lethal</li>
			<li>Vanilla Weapons Expanded - Laser</li>
			<li>Vanilla Trading Expanded</li>
			<li>Vanilla Textures Expanded</li>
			<li>Vanilla Plants Expanded - Succulents</li>
			<li>Vanilla Furniture Expanded - Spacer Module</li>
			<li>Vanilla Furniture Expanded - Security</li>
			<li>Vanilla Furniture Expanded - Props and Decor</li>
			<li>Vanilla Furniture Expanded - Production</li>
			<li>Vanilla Furniture Expanded - Medical Module</li>
			<li>Vanilla Furniture Expanded - Farming</li>
			<li>Vanilla Furniture Expanded - Art</li>
			<li>Vanilla Furniture Expanded - Architect</li>
			<li>Vanilla Events Expanded</li>
			<li>Vanilla Books Expanded</li>
			<li>Vanilla Base Generation Expanded</li>
			<li>Vanilla Armour Expanded</li>
			<li>Replace Stuff</li>
			<li>Pick Up And Haul</li>
		</names>
	</modList>
</savedModList>
```

**Comment by AndiLeni** [comment] 2023-08-12 14:16
It seems like it this is not related to Replimat and was instead a bad timing with another ingame object which was instead draining energy. 
Sorry about the confusion.

**Comment by sumghai** [comment] 2023-08-12 20:33
You haven't narrowed down you modlist to the bare minimum combination of mods necessary to reproduce this issue, and you haven't described any reproduction steps at all.

Looking at your screenshot, the Hopper power consumption is actually working exactly as designed. The hopper has an _**idle**_ power consumption of 2000 W, but also has an _**active**_ state power consumption of 20000W when it is processing raw food. This is shown as a stat in the Hopper's inspect window:

![image](https://github.com/sumghai/Replimat/assets/4993380/484a3223-3179-49c3-802b-5a8beb1e0da8)

I'm closing this issue, as this is working as intended.

**Closed by sumghai** 2023-08-12 20:33 UTC
Labels: Bug
