### ISSUE TITLE
Replimat terminals can only connect to computer via vanilla power conduits

### ISSUE THREAD

**Issue by CombatTentacles** [sumghai/Replimat#23] opened 2019-07-17 22:48 UTC
Specifically, my prison and the room containing the replimat computer and feedstock tank are in separate buildings, connected only through subsurface conduits from [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1609226728). The prison replimat terminal gives the "no connection to replimat computer" error message, whereas the terminal in my dining room that's connected to the tank and computer with standard in-wall power conduits works as intended. I haven't tested the conduits added by the Carbon mod but I expect it would be the same story.

**Comment by sumghai** [comment] 2019-07-18 14:16
I'll need a big more time to investigate this further, but my first impressions are:

- Subsurface Conduits defines its own ThingClass, which is incompatible with Replimat's lookup for vanilla power conduits

- Carbon mod conduits should be fine, as they are based on the vanilla conduits

**Comment by sumghai** [comment] 2019-07-21 13:23
@CombatTentacles - I have not been able to reproduce this issue, with a minimal setup of Core, Replimat and either Carbon mod -or- Subsurface Conduits.

* Carbon mod conduits work just fine at connecting Replimat components, because they inherit from the vanilla `PowerConduit` XML def

* Surprisingly, Subsurface Conduits also works. Reverse-engineering the source code of the Assembly reveals that all that the `MUR_SubsurfaceConduit.SubsurfaceConduit` thingClass does is to draw the conduit on a different layer (essentially hiding it from view), while the underlying XML def indicates that it uses the same comps as the vanilla Power Conduits*

*In fact, the entire Subsurface Conduit mod could have actually be completely made just with defs alone without a plugin, just by specifying the correct altitude drawlayer to hide the conduit.

Anyway, @CombatTentacles, can you please try again, this time with a stripped-down savegame with only Replimat and the conduit mod? This is just so we can confirm the basic setup actually still works on your end, before we investigate whether a third mod is causing compatibility issues.

**Comment by sumghai** [comment] 2019-07-26 13:16
Closing due to no follow-up from @CombatTentacles.

**Closed by sumghai** 2019-07-26 13:16 UTC
Labels: Bug
