### ISSUE TITLE
Pawns stand instead of retrieving meals

### ISSUE THREAD

**Issue by DWeidmann** [sumghai/Replimat#58] opened 2021-11-23 22:42 UTC
**Describe the bug:**  
Pawns stand still instead of retrieving meals

**Expected behavior:**  
Pawns retrieve meals

**Steps to reproduce:**  

1.Build replimat
2.Observe that some pawns do not retrieve meals

**Additional information:**

## System and Game Configuration
**Operating System:**
windows 10 
**Physical RAM:**
16 
**RimWorld base game version:**
1.3 
**RimWorld DLCs loaded:**
royalty ideology 
**Replimat mod version:**
1.2.12 
**Replimat mod downloaded from:**
steam
**Your mod list:** 
Core
Harmony
Royalty
Ideology
Replimat 1.2.12

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2021-11-24 00:24
@DWeidmann What ideology/memes/precepts does your colony have?

**Comment by DWeidmann** [comment] 2021-11-24 04:42
![image](https://user-images.githubusercontent.com/48780007/143176168-aa392bbe-71e8-40a5-bb4b-b0af6b04d13a.png)

**Comment by sumghai** [comment] 2021-11-26 03:55
In my test save, I wasn't able to fully replicate your exact ideology, because the **Torture** and **Ocular trees** precepts are apparently from third-party mods you failed to mention in your report.

More importantly, my pawns were able to replicate meals just fine with the list of mods you currently specified.

Please check your modlist again, and get back to me when you've found the conflicting third-party mod(s) causing this issue.

**Comment by sumghai** [comment] 2021-11-26 08:08
@DWeidmann There's no need to close this issue - instead, check your modlist, identify the conflicting mods, determine the steps needed to reproduce the bug, and you can then go back and edit your initial report.

**Closed** 2021-11-29 21:36 UTC
Labels: Bug, Needs More Info
