### ISSUE TITLE
Replimat Cadaver Processor cannot be spawned when Misc. MAI and HAR framework mods are active

### ISSUE THREAD

**Issue by volpol** [sumghai/Replimat#65] opened 2022-04-26 16:38 UTC
**Describe the bug:**  
Replimat Cadaver Processor cannot spawn due to NullReferenceException. The symptoms are the same as in #49
The bug is only triggered if the Mod "Misc. MAI" from https://github.com/HaploX1/RimWorld-Miscellaneous_Mods
AND "Humanoid Alien Races" are both loaded. "Humanoid Alien Races", while not a dependency of "Misc. MAI", is needed by other Mods I use. 

**Expected behavior:**  
Replimat Cadaver Processor can be constructed/spawned and used normally

**Steps to reproduce:**  

Start a new game with "Humanoid Alien Races" and "Misc. MAI" active and try placing/constructing the Replimat Cadaver Processor anywhere.
The same approach as in #49 works.

**Additional information:**

Log excerpt:
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at Replimat.ModCompatibility.AlienCorpseHasOrganicFlesh (Verse.ThingDef def) [0x00028] in <148fd89434df4ceca6591a4c9adbeb56>:0 
  at Replimat.Building_ReplimatCorpseRecycler+<>c.<GetParentStoreSettings>b__21_1 (Verse.ThingDef def) [0x00000] in <148fd89434df4ceca6591a4c9adbeb56>:0 
  at System.Collections.Generic.HashSet`1[T].RemoveWhere (System.Predicate`1[T] match) [0x0003a] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at Replimat.Building_ReplimatCorpseRecycler.GetParentStoreSettings () [0x0004f] in <148fd89434df4ceca6591a4c9adbeb56>:0 
  at RimWorld.StorageSettings..ctor (RimWorld.IStoreSettingsParent owner) [0x00010] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Replimat.Building_ReplimatCorpseRecycler.PostMake () [0x00006] in <148fd89434df4ceca6591a4c9adbeb56>:0 
  at Verse.ThingMaker.MakeThing (Verse.ThingDef def, Verse.ThingDef stuff) [0x000c7] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Verse.DebugThingPlaceHelper.DebugSpawn (Verse.ThingDef def, Verse.IntVec3 c, System.Int32 stackCount, System.Boolean direct, Verse.ThingStyleDef thingStyleDef) [0x00013] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Verse.DebugThingPlaceHelper+<>c__DisplayClass2_2.<TryPlaceOptionsForStackCount>b__3 () [0x0000b] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Verse.DebugTool.DebugToolOnGUI () [0x00018] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Verse.DebugTools.DebugToolsOnGUI () [0x00007] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x000be] in <b1553c0a22524ba7875e2196f13edca5>:0 
  at Verse.Root.OnGUI () [0x0003d] in <b1553c0a22524ba7875e2196f13edca5>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Root:OnGUI ()

## System and Game Configuration
**Operating System:** Linux Devuan 4.0 Chimaera
**Physical RAM:** 32GB
**RimWorld base game version:** 1.3.3287 rev1379
**RimWorld DLCs loaded:** Royalty, Ideology
**Replimat mod version:** 1.3.0
**Replimat mod downloaded from:** GitHub
**Your mod list:** 
Harmony 2.2.1
Humanoid Alien Races 1.2-137-g56a003e
Replimat 1.3.0 (1.3.0-5-g56db474)
Misc. Core 1.3.2 as of 2022-04-08 (a6f6a4e3c3b37e87bc5ca382e59fa47284ae93cd)
Misc. MAI 1.3.1 as of 2022-04-08 (a6f6a4e3c3b37e87bc5ca382e59fa47284ae93cd)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2022-04-27 13:48
I've successfully reproduced this bug on my end.

Unlike the vast majority of robot/android races mods that use the HAR framework, the Misc MAI robots are coded using completely custom classes, so the `AlienCorpseHasOrganicFlesh()` method can't treat the latter like typical alien races in order to check their flesh type.

The easiest fix for Misc MAI & HAR compatibility with Replimat is to first check if a pawn is humanlike *AND* a valid HAR alien - MAI robots will return `true` for the former and `false` for the latter, which will then (correctly) cause the result to default to `false.

However, I will also need to do a fix for Misc MAI *without* HAR to prevent them from being processed, which is a bit more difficult because Haplo's non-HAR implementation sometimes treats the MAI robots as being functionally identical to regular humans.

**Comment by sumghai** [comment] 2022-04-27 23:20
> Thanks for the prompt response. There are actually several compatibility issues between Misc. MAI and Replimat and MedPod (like MAI being unable to get a meal from a Replimat Terminal probably due to Liquor being the only valid "Meal") but nothing game breaking like this one.

My impression of Misc MAI from back in B17/B18 was that the robots don't actually need to consume any nutrition.

Given the unusual way Haplo coded these robots, the best I can do is to fix obvious game-breaking bugs. Otherwise, as @Dubwise56 and I previously agreed, it's not worth the effort patching for third-party mods that deviate too far from base game / maintstream behaviour.

**Comment by sumghai** [comment] 2022-04-28 03:11
@volpol - Okay, I've fixed the NullRef when both Misc MAI and HAR and active, as well as removing MAI robot corpses from the Processors if HAR isn't active.

Please try the following dev build:

https://github.com/sumghai/Replimat/archive/139ece32086ebf8a4f47bbca5cd318d6499012f3.zip

**Comment by volpol** [comment] 2022-04-28 09:21
I confirm that Cadaver Processor can now be built and used normally. Thank you. And further observation showed that the issue with MAI not being able to get a meal from a Terminal is not one of compatibility between Misc. MAI and Replimat as other Pawns triggered it later as well as they were trying to get a meal to feed a downed animal with an alien race.

**Comment by sumghai** [comment] 2022-04-28 09:51
Cool, thanks for confirming that the fix works! I'll mark this one as done.

As for pawns being unable to replicate meals for downed animals, that'll need to be treated as a separate issue/bug.

**Comment by volpol** [comment] 2022-04-30 12:54
A little update. Setting MAI's flesh to Mechanoid kills its natural healing. I only noticed now because MAI was being healed by the Medpod and currently my colony doesn't have one yet. It might be an overkill anyway as I tried disabling the corresponding patch, thus leaving fleshType as Normal and there were no adverse effects so far. Pawns refuse to haul MAI corpse to the Cadaver Processor so no processing is attempted. Considering how niche this issue seems to be it's fine if you don't invest any more effort into this. Just letting you know. (Commented on the wrong issue originally)

**Comment by sumghai** [comment] 2022-05-01 09:00
Ooh, right, so *that's* why Haplo set MAIs to have normal flesh type. I can definitely remove that patch.

Yeah, I know that pawns generally don't haul dead MAIs to Cadavers Processors, but ideally they shouldn't be listed in the storage settings anyway. I may have to manually hardcode Replimat to hide MAI corpses altogether, like what I did for the hologram pawns from Save Our Ship 2.

**Comment by volpol** [comment] 2022-05-07 11:04
I don't actually see it listed in the settings for the Cadavers Processors. Am I overlooking something?
![cpsettings](https://user-images.githubusercontent.com/22329423/167251518-7c3c12a1-9428-43ab-8b36-f152470831ab.png)

**Comment by sumghai** [comment] 2022-05-07 20:07
Ah, the reason MAI robot corpses aren't showing up for you is because of a specific interaction between the Replimat dev build, HAR and Misc MAI.

Consider the [`AlienCorpseHasOrganicFlesh()` method](https://github.com/sumghai/Replimat/blob/df5e1cfab6f854954d25bdc8941b2e40d1d5c113/Source/ModCompatibility.cs#L26):

```csharp
public static bool AlienCorpseHasOrganicFlesh(ThingDef def)
{
	ThingDef corpseAlienRace = ThingDef.Named(def.ToString().Substring("Corpse_".Length));

	if (corpseAlienRace.race.Humanlike && corpseAlienRace is ThingDef_AlienRace raceDef)
	{                
		return raceDef?.alienRace.compatibility.IsFlesh ?? true;
	}

	return false;
}
```

Because MAI robot pawns will always cause the `corpseAlienRace is ThingDef_AlienRace raceDef` part to return `false`, it breaks out of the `if()` block and causes the whole method to return `false`, ultimately hiding MAI robot corpses from the Cadaver Processor in your specific case.

**However**, if a player *isn't* running HAR, then the aforementioned compatibility method isn't run, so MAI robot corpses would now show up in the Processor's storage settings.

For #49, I had to [hard-code the removal of SOS2 hologram corpses](https://github.com/sumghai/Replimat/blob/df5e1cfab6f854954d25bdc8941b2e40d1d5c113/Source/Building_ReplimatCorpseRecycler.cs#L108), since like MAI robots they are not HAR-compatible races. While the easiest thing to do would be to also hard-code a couple of lines for MAI as well, that would mean recoding and recompile the assembly every time I want to blacklist a non-HAR robot race. 

A better approach would be for me to expose something in XML to allow XPath patching of corpses that the Cadaver Processor can/cannot recycle, for ease of future maintenance by myself and other modders.

**Comment by volpol** [comment] 2022-05-08 09:05
Ah, that makes sense. Right, AlienCorpseHasOrganicFlesh() is only called when HAR is active. This whole thing is sort of unsatisfactory. The MAIs should probably have Mechanoid type fleshType with healing only during rest in their charging station. Both their MeatAmount and LeatherAmount is set to 0, but traders still routinely stock up on "AI Pawn E" meat. How? Anyway is that something that can be additionally checked for now? The meat amount that is. So, normal fleshType but no meat is not suitable? This would fix the non-HAR case and should be general enough approach that wouldn't need to be removed later even if you implement that XPath patching method.

**Comment by sumghai** [comment] 2022-05-08 23:49
Yeah, fair point. Filtering out pawns with 0 `MeatAmount` seems to work nicely for both Misc MAI robot pawns and SOS2 holograms.

**Comment by sumghai** [comment] 2022-05-08 23:57
@volpol - Alright, please try this new dev build with Misc MAI, as well as ***with*** and ***without*** HAR:

https://github.com/sumghai/Replimat/archive/d89b7939d373101856d7d62479d0630a2527b026.zip

**Comment by sumghai** [comment] 2022-05-13 23:46
In the absence of further feedback, I'm going to assume that MAI robot pawns are being filtered out properly.

Closing.

**Closed** 2022-05-13 23:46 UTC
Labels: Bug

**Comment by volpol** [comment] 2022-05-14 08:04
I only got around to test it today. I wasn't aware of a deadline to report back on a non-critical issue (none were specified). And, as expected, the MAI corpses are correctly filtered out in both HAR and non-HAR cases.
