### ISSUE TITLE
Pawns not hauling raw food to hoppers 

### ISSUE THREAD

**Issue by bauch1234** [sumghai/Replimat#75] opened 2022-11-27 20:14 UTC
**Describe the bug:**  
pawns rarely hauling to the hopper

**Expected behavior:**  
them to keep the hoppers topped off with food when the stockpile zone is full of food

**Steps to reproduce:**  

1. place down some hoppers and then like a 8x8 square of meat/vegies pawns will haul a lot a first then they just stop coming by rarely to put more in the hopper even when silos are empty and they have no other jobs but hauling 
2.
3.

**Additional information:**

## System and Game Configuration
**Operating System:**  Microsoft Windows 10 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.4.3558
**RimWorld DLCs loaded:** all
**Replimat mod version:** 1.4.4
**Replimat mod downloaded from:** steam
**Your mod list:** Harmony 2.2.2,hugslib 10.0.1,replimat1.4.4,dubs rimatomics 1.7.25

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2022-12-01 07:31
I cannot reproduce the issue as described, using the mods and versions listed in the report.

In my own test environment, pawn with the default automatic work priorities will constantly haul raw food to hoppers if there are no other pressing tasks.

Please check your pawn's work priorities and the relative storage priorities of all Replimat Hoppers, shelves and stockpile areas.

**Comment by bauch1234** [comment] 2022-12-03 03:07
i verified all of my priorities is are good and its still happening, however it doesnt happen on a dev test environment guess my save broke time to start another

**Comment by sumghai** [comment] 2022-12-03 03:15
Closed as irreproducible.

**Closed by sumghai** 2022-12-03 03:15 UTC
Labels: Bug
