### ISSUE TITLE
Error when loading Dubs Bad Hygiene and Replimat together

### ISSUE THREAD

**Issue by msnspk** [sumghai/Replimat#79] opened 2023-05-20 22:45 UTC
**Describe the bug:**  
When [Dubs Bad Hygiene](https://steamcommunity.com/sharedfiles/filedetails/?id=836308268) and Replimat are loaded in the same mod list, regardless of order, an error occurs when the game loads.

**Expected behavior:**  
The game should load without errors.

**Steps to reproduce:**  

1. Reset mod list to zero mods
1. Add Dubs Bad Hygiene to mod list (any order)
2. Add Replimat to mod list (any order)
3. Launch the game, experience error

**Additional information:**

```
Could not resolve cross-reference to Verse.ThingDef named ReplimatSewageRecycler (wanter=excludedThingDefs)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.ThingDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.ThingDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

## System and Game Configuration
**Operating System:** Arch Linux 64-bit
**Physical RAM:** 32 GB
**RimWorld base game version:** 1.4.3704
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech
**Replimat mod version:** Version 1.4.6 - 18 March 2023
**Replimat mod downloaded from:** Steam
**Your mod list:**
* Core
* Royalty
* Ideology
* Biotech
* Replimat 1.4.6 - 18 March 2023
* Dubs Bad Hygiene 3.0.2228 - 14 November 2023

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by msnspk** [comment] 2023-05-20 22:45
Let me know if there is any other information you want or anything you want me to test, happy to oblige.

**Comment by sumghai** [comment] 2023-05-21 01:00
Issue could not be reproduced in RW 1.4.3704, with Replimat 1.4.6 and BDH v3.0.2228. DLCs had no effect.

No error messages were shown during game startup, and the Replimat Sewage Recycler mentioned in the error log works just fine.

Does the issue occur on a new save?

**Comment by sumghai** [comment] 2023-06-16 20:36
Closing due to lack of follow-up.

**Comment by nfowler** [comment] 2023-08-23 22:28
I am having this exact same issue.

Specific stack trace as follows:
```Could not resolve cross-reference to Verse.ThingDef named ReplimatSewageRecycler (wanter=excludedThingDefs)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.ThingDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.ThingDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

System and Game Configuration

Operating System: EndeavourOS
Physical RAM: 32 GB
RimWorld base game version: 1.4.3704
RimWorld DLCs loaded: Royalty, Ideology, Biotech
Replimat mod version: Version 1.4.7
Replimat mod downloaded from: Steam
Your mod list:
- Harmony
- Rimworld
- Rimworld - Royalty
- Rimworld - Ideology
- Rimworld - Biotech
- Replimat 1.4.7
- Dubs Bad Hygiene 3.0.2228

With this modlist, I loaded into a Dev quicktest and used godmode to test if the Sewage Recycler still worked. It did not appear in the architect menu. My OS is closely related to Arch Linux, as used by msnspk. Not sure if this is a coincidence, or if this is a Linux-only bug of some sort.

**Comment by nfowler** [comment] 2023-08-23 22:50
As a small follow-up, I booted into Windows and loaded the game with the exact same modlist, exact same mod versions. The error did not occur.

**Comment by sumghai** [comment] 2023-08-24 06:23
Issue still cannot not be reproduced in RW 1.4.3704, with Replimat 1.4.7 and DBH 3.0.2228 on Windows 11 Version 22H2 (OS Build 22621.2215). 

Sounds like a Linux-specific issue. Could you check if you are running the latest version of Harmony?

**Comment by nfowler** [comment] 2023-08-24 15:52
Running same mod list, with Harmony Lib v2.2.2.0, Mod v1.5.0.0. Replimat and DBH same version. RimWorld same version. Running Windows 10.0.19045 Build 19045. Error does not occur.

Running same mod list, with same Harmony versions, and same mod version, on EndeavourOS. Error does occur.

This is definitely a Linux-only bug.

Of potential note, that I neglected to mention but could narrow down what's happening, the error always occurs three times in the log.

**Comment by sumghai** [comment] 2023-08-25 06:25
Right, so it is an OS-specific issue. Since I don't run Linux myself, I only have the stacktrace to go by.

The only thing I can think of that *could* be problematic is the following XPATH PatchOp that uses a `MayRequire` to conditionally exclude the Sewage Recycler from trader inventory (if DBH is installed). However, `MayRequire` is valid for both DLCs and mods, so surely if there was a problem, Linux would complain about `MayRequire`s in general.

**Comment by nfowler** [comment] 2023-09-01 18:28
So I've solved this issue. Linux file paths use forward slashes ("/"), while Windows uses back slashes ("\\"). In the `LoadFolders.xml` file, which detects if Dub's Bad Hygiene is active, you used back slashes to point towards the Compatibility folder.

If I replace the line:
`<li IfModActive="Dubwise.DubsBadHygiene">Compatibility\DubsBadHygiene</li>`
With:
`<li IfModActive="Dubwise.DubsBadHygiene">Compatibility/DubsBadHygiene</li>`
I no longer get this error, and the Sewage Recycler correctly appears in the game.

However, I'm not sure if this breaks compatibility in Windows.

**Comment by sumghai** [comment] 2023-09-01 20:50
Fascinating! I just tried changing the slash direction on my end with Windows, and it seems to work fine for me too.

But just to confirm I've done it correctly, would you be able to manually install the following dev build of Replimat, and confirm the fix works?:

https://github.com/sumghai/Replimat/archive/265c7b2e0868a925795b2846f38a5d715dd01af6.zip

**Comment by nfowler** [comment] 2023-09-01 21:18
Error does not occur while using the given dev build, and the sewage recycler correctly appears in-game. Works perfectly for me.

**Comment by sumghai** [comment] 2023-09-01 21:42
Nice, I can finally close this off for good. Thanks for the help!

**Closed by sumghai** 2023-09-01 21:42 UTC
Labels: Bug
