### ISSUE TITLE
Incompatibility with Human Alien Races.  

### ISSUE THREAD

**Issue by bauch1234** [sumghai/Replimat#85] opened 2024-04-19 02:51 UTC
**Describe the bug:**  
 This error with HAR https://gist.github.com/HugsLibRecordKeeper/e08eb6d7b329066e598e90923dbd1874 
**Expected behavior:**  
this error not to occur, they have been compatible since 1.3  

**Steps to reproduce:**  

1. launch game with both replimat and HAR
2.place cadaver processer
3.error

**Additional information:**

[](https://gist.github.com/HugsLibRecordKeeper/e08eb6d7b329066e598e90923dbd1874)

## System and Game Configuration
**Operating System:** Microsoft Windows 11 pro (64-bit) 
**Physical RAM:**   16.0 GB
**RimWorld base game version:** 1.5.4069
**RimWorld DLCs loaded:** all
**Replimat mod version:** 1.5.1
**Replimat mod downloaded from:** steam
**Your mod list:** harmony 2.3.1.0 hugslib 11.0.3 Human Alien Races unable to find version but its newest from steam

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x ] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x ] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2024-04-19 06:11
Duplicate of #84 - a combo bug caused by a specific interaction between HAR and the Anomaly DLC (which your logs states you're also running).

Already fixed as of the v1.5.2 update.

**Closed by sumghai** 2024-04-19 06:11 UTC
Labels: Bug
