### ISSUE TITLE
Pawns constantly hauling kibble and hay between Animal Feeders

### ISSUE THREAD

**Issue by bauch1234** [sumghai/Replimat#71] opened 2022-11-13 03:51 UTC
**Describe the bug:**  
colonist haul kibble and hay around between animal feeders excessively 

**Expected behavior:**  
as in 1.3 to leave the kibble and hay where it is and let it be dispensed as needed

**Steps to reproduce:**  

1.place down multiple animal feeders and them all be at like half stacks of kibble or hay
2.
3.

**Additional information:**

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:**  16.0 GB
**RimWorld base game version:** 1.4.3542(64bit)
**RimWorld DLCs loaded:** royalty,ideo.,biotech
**Replimat mod version:** 1.4.2
**Replimat mod downloaded from:** steam
**Your mod list:** Loaded mods:
harmony 2.2.2,hugslib10.0.1,rimatomics1.7.25

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment] 2022-11-19 02:24
I cannot reproduce the issue as currently described.

What are the storage priorities for all of your animal feeders? Do you have any other stockpiles that accept kibble/hay/synthmeat at a higher storage priority than your feeders?

**Comment by bauch1234** [comment] 2022-11-22 22:47
The storage priorities are critical on all of the terminals, and there is no other storage zones for kibble or hay. sorry for the late reply

**Comment by sumghai** [comment] 2022-11-23 05:40
Closed as the issue occurred on OSI Layer 8.

**Closed by sumghai** 2022-11-23 05:40 UTC
Labels: Invalid / Won't Fix / No Follow-Up, Bug
